/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
/* Header for class opencvdemo_com_ndkopencvtest_OpenCVClass */

using namespace cv;
#ifndef _Included_opencvdemo_com_ndkopencvtest_OpenCVClass
#define _Included_opencvdemo_com_ndkopencvtest_OpenCVClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opencvdemo_com_ndkopencvtest_OpenCVClass
 * Method:    faceDetection
 * Signature: (J)V
 */
 void detect(Mat& frame);
JNIEXPORT void JNICALL Java_opencvdemo_com_ndkopencvtest_OpenCVClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
